---
session_name: dotfiles
working_dir: ~/Library/CloudStorage/Dropbox/notes/org
windows:
  - name: dotfiles
    working_dir: ~/git/dotfiles
    layout: "d07d,123x68,0,0,0"
  - name: org
    layout: "d07e,123x68,0,0,1"
