[[prompt_parts]]
type = "Tmux"
format = "{windows_status} "

[[prompt_parts]]
type = "GitBranch"
truncate = { max_len = 30, ellipsis_str = ".." }
format = "{branch_name} "

[[prompt_parts]]
type = "CurrentDir"
# truncate = { max_len = 300, ellipsis_str = "..", elide_from_start = true } # This is problematic because the truncation should be from the start
format = " {current_dir} "
relative_to_git_root = true
