-- local opts = {
--   log_level = 'debug',
--   auto_session_enable_last_session = true,
--   auto_session_root_dir = vim.fn.stdpath('data').."/sessions/",
--   auto_session_enabled = true,
--   auto_save_enabled = true,
--   auto_restore_enabled = true,
-- }

-- -- Recommeded by README
-- vim.o.sessionoptions="blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal"
-- require('auto-session').setup(opts)
