idle_bg = "#363a4f"
idle_fg = "#cad3f5"
info_bg = "#8aadf4"
info_fg = "#24273a"
good_bg = "#a6da95"
good_fg = "#24273a"
warning_bg = "#eed49f"
warning_fg = "#24273a"
critical_bg = "#ed8796"
critical_fg = "#24273a"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
