idle_bg = "#ccd0da"
idle_fg = "#4c4f69"
info_bg = "#1e66f5"
info_fg = "#eff1f5"
good_bg = "#40a02b"
good_fg = "#eff1f5"
warning_bg = "#df8e1d"
warning_fg = "#eff1f5"
critical_bg = "#d20f39"
critical_fg = "#eff1f5"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
