idle_bg = "#313244"
idle_fg = "#cdd6f4"
info_bg = "#89b4fa"
info_fg = "#1e1e2e"
good_bg = "#a6e3a1"
good_fg = "#1e1e2e"
warning_bg = "#f9e2af"
warning_fg = "#1e1e2e"
critical_bg = "#f38ba8"
critical_fg = "#1e1e2e"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
