idle_bg = "#414559"
idle_fg = "#cad3f5"
info_bg = "#8caaee"
info_fg = "#303446"
good_bg = "#a6d189"
good_fg = "#303446"
warning_bg = "#e5c890"
warning_fg = "#303446"
critical_bg = "#e78284"
critical_fg = "#303446"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
