[user]
name = "David Assefa Tofu"
email = "davidtofu2018@gmail.com"

[ui]
# I thought this one would work but I think it's the line after that actually works.
diff-formatter = "difft"
diff.tool = "difft"
