-- vim.api.nvim_create_autocmd({ "BufCreate", "BufNewFile", "BufEnter" }, {
-- 	pattern = "*.tsx",
-- 	callback = function()
-- 		-- I copied over the formatoptions from a `.ts file because I preferred how
-- 		-- when you are typing comments, and you press enter, the new line has a comment prefix too.
-- 		vim.opt_local.formatoptions = {
-- 			c = true,
-- 			j = true,
-- 			l = true,
-- 			o = true,
-- 			q = true,
-- 			r = true,
-- 		}
-- 	end,
-- })
