#!/usr/bin/env bash

if [[ ! -z "$QUTE_URL" ]]; then
  hostname_arg="--url=$(echo $QUTE_URL | sed -e 's/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/')"
else
  hostname_arg=""
fi

# This relies on a hack that my passwords wo'nt contain 🤓
prompts=()
passwords=()
bw list items "$hostname_arg" | jq -r '.[] | .name + "🤓" + .login.username  + "🤓" + .login.password'  |
  while IFS=🤓 read name username password; do
    prompts+=("$name  | $username")
    passwords+=("$password")
  done


# 
# from subprocess import Popen
# import sys
# import os
# from urllib.parse import urlparse
# import pyperclip
# 
# url = os.environ.get("QUTE_URL", "")
# 
# if url:
#     hostname = urlparse(url).hostname
# else:
#     raise Exception("No QUTE_URL environment variable.")
# 
# Popen(["bw", "list", "items", 
# pyperclip.copy("asdf")
