#!/usr/bin/python3

from urllib.parse import urlparse
import sys
import os
import json
from pyperclip import copy
from subprocess import PIPE, Popen

if url := os.environ.get("QUTE_URL", ""):
  hostname_args = [ "--url", urlparse(url).hostname]
else:
  hostname_args = []


proc =  Popen(["bw", "list", "items"] + hostname_args, stdout=PIPE)
if proc.stdout:
    items = json.loads(proc.stdout.read().decode())
else:
    print("Proc has no stdout")
    sys.exit()

pwds = []
prompts = []

for i, item in enumerate(items):
    if (login:= item.get("login")) and login.get("password"):
        pwds.append(item["login"]["password"])
        prompts.append(str(i) + " | " + item["name"] or "NO NAME"  + " | " + item["login"]["username"] or "NO USERNAME")

proc =  Popen(["fzf", ],  stdin=PIPE, stdout=PIPE, text=True)
stdout, stderr = proc.communicate(input="\n".join(prompts))
if proc.stdout:
    idx = int(stdout.strip().split(" | ")[0])
    copy(pwds[idx])
else:
    print("Proc has no stdout")
    sys.exit()

