[user]
name = "David Assefa Tofu"
email = "davidtofu2018@gmail.com"

[ui]
pager = [ "less", "-R" ]
# pager = "nvim_pager"
diff-formatter = "difft"
default-command = "log"
# diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
# diff-editor = "hunks_nvim"

[aliases]
# https://danverbraganza.com/writings/most-frequent-jj-commands
tug- = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@"]

drop = ["abandon"]
d = ["diff"]


[merge-tools.hunks_nvim]
# program = "nvim"      # Defaults to the name of the tool if not specified
# edit-args = [ "-c", "DiffEditor $left $right $output"]

[merge-tools.diffconflicts]
program = "nvim_pager"
merge-args = [
	"-c", "let g:jj_diffconflicts_marker_length=$marker_length",
	"-c", "JJDiffConflicts!", "$output", "$base", "$left", "$right",
]
merge-tool-edits-conflict-markers = true


# https://docs.jj-vcs.dev/latest/config/#automatic-tracking-of-bookmark
[remotes.origin]
auto-track-bookmarks = "*"

[revsets]
# Default revset is: present(@) | ancestors(immutable_heads().., 2) | trunk()
# We subtract empty leaf commits to hide idle workspace working copies (and
# other empty heads), while keeping the current workspace's @ visible

[revset-aliases]
"common_ancestor_with_main(r)" = "heads(::r & ::main)"
empty_heads = "empty() & heads(all())"
empty_heads_except_current = "empty() & heads(all()) & ~@"

by_me = 'author_email("52462475+dnaaun@users.noreply.github.com") | author_email("davidtofu2018@gmail.com")'

the_usual = "(present(@) | ancestors(immutable_heads().., 2) | trunk())  & ~empty_heads_except_current"

to_squash = 'subject(regex:"^TO SQUASH")'

"log()" = "the_usual & (by_me | ::main)"

[fileset-aliases]
tests_and_docs = '(glob:"**/*test*.*" | glob:"**/*Tests.swift" | glob:"**/*.md")'

